
export enum ResultatAnalysePhrase {
  aucun,
  commentaire,
  section,
  aide,
  regle,
  synonyme,
  abreviation,
  action,
  activerParametre,
  afficherCompteur,
  elementAvecPosition,
  elementSansPosition,
  pronomDemontratifTypeAttribut,
  pronomPersonnelPosition,
  pronomPersonnelAttribut,
  pronomPersonnelContenuListe,
  positionElement,
  propriete,
  reaction,
  capacite,
  type,
  precisionType,
}
