
export enum ResultatAnalysePhrase {
  aucun,
  commentaire,
  section,
  aide,
  regle,
  synonyme,
  action,
  desactiver,
  elementAvecPosition,
  elementSansPosition,
  pronomDemontratifTypeAttribut,
  pronomPersonnelPosition,
  pronomPersonnelAttribut,
  propriete,
  reaction,
  capacite,
  type,
  precisionType,
}
