
export enum EClasseRacine {
  intitule = 'intitule',
  element = 'element',
  lieu = 'lieu',
  objet = 'objet',
  vivant = 'vivant',
  animal = 'animal',
  personne = 'personne',
  porte = 'porte',
  contenant = 'contenant',
  support = 'support',
  // types spéciaux
  joueur = 'joueur',
  inventaire = 'inventaire',
}

export enum EEtatsBase {
  present = 'présent',
  absent = 'absent',
  intact = "intact",
  deplace = "déplacé",
  modifie = "modifié",
  cache = 'caché',
  couvert = 'couvert',
  invisible = 'invisible',
  accessible = 'accessible',
  inaccessible = 'inaccessible',
  decoratif = 'décoratif',
  possede = 'possédé',
  disponible = 'disponible',
  occupe = 'occupé',
  porte = 'porté',
  denombrable = 'dénombrable',
  indenombrable = 'indénombrable',
  mangeable = 'mangeable',
  buvable = 'buvable',
  ouvrable = 'ouvrable',
  ouvert = 'ouvert',
  ferme = 'fermé',
  verrouillable = 'verrouillable',
  verrouille = 'verrouillé',
  deverrouille = 'déverrouillé',
  // LUMINEUX = 'lumineux',
  eclaire = 'éclairé',
  // SOMBRE = 'sombre',
  obscur = 'obscur',
  allume = 'allumé',
  eteint = 'éteint',
  marche = 'marche',
  arret = 'arrêt',
  parlant = 'parlant',
  muet = 'muet',
  opaque = 'opaque',
  transparent = 'transparent',
  fixe = 'fixé',
  transportable = 'transportable',
}
